repository: kadenn/my-resume
favicon: images/favicon.ico

# Content configuration version
version: 2

name: Kagan Demirhindi
title: Full Stack Developer
email: k.demirhindi@gmail.com
# website: demirhindi.net

# Dark Mode (true/false/never)
darkmode: never

github_username: kadenn
linkedin_username: kagan-demirhindi
instagram_username: kagandemirhindi

additional_links:
  - title: demirhindi.net
    icon: fas fa-globe
    url: http://demirhindi.net/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# about_title: About Me
about_profile_image: images/profile.png
about_content: |
  Hi, my name is Kagan, and I'm a full stack web developer with over 4 years of experience.
  I enjoy developing full stack web applications using the latest technologies to translate business requirements and logic into code.
  My areas of expertise include: <mark>VueJS</mark>, <mark>JavaScript</mark>, <mark>Python</mark>, <mark>Docker</mark>, and <mark>Golang</mark>.

  I've been interested in computers since I was a child.
  My passion for programming began when I created my own Minecraft server to play with friends.
  As I grew older, I continued to learn and explore new technologies.
  I pursued a degree in computer engineering to turn my passion into a career.
  I'm adept at learning and implementing new concepts and tools quickly.
  I believe in understanding concepts rather than memorizing them, and I always strive to think critically and creatively.

content:
  - title: Experience
    layout: list # (list/text)
    content:
    - layout: left
      title: Teamwork, Belfast
      link: www.teamwork.com
      sub_title: Full Stack Developer
      caption: November 2021 - Present
      description: |
        *At Teamwork, we create business management applications that make teams more efficient, organized, and happy. 
        Our tools include work management, helpdesk, chat, sales CRM, and content collaboration workspace software. 
        They're used by teams of all sizes, across all industries â€” from education to financial services.*

    - layout: left
      title: CardAlpha, London
      link: www.cardalpha.com
      sub_title: Full Stack Developer
      caption: September 2020 - June 2021 (10 months)
      description: |
        *CardAlpha is a financial technology company based in London, England.
        CardAlpha's ePOS App converts a small business owner's tablet or smartphone device into a powerful electronic cash register.*

        - Gained insights into the working culture in London.
        As a full stack developer, I learned to be outcome-focused.
        Working in a small team, I had the opportunity to work closely with the CEO and CTO to define our product.

        - Developed microservices in <mark>Golang</mark> that communicate over <mark>gRPC</mark>.
        <mark>Dockerized</mark> and deployed on a <mark>Google Kubernetes Engine</mark> cluster.

        - Integrated our API with our partner bank's API, automating the merchant underwriting and onboarding process.
        This significantly reduced the time between signing a contract and processing transactions to just a few hours.

        - Translated an existing iOS app into a web-based <mark>React</mark> app.
        Developed CardAlpha's web-based mobile app in <mark>TypeScript</mark> using <mark>Ionic</mark>, <mark>React</mark>, and <mark>Capacitor</mark>.
        Used native SDKs by developing <mark>Capacitor</mark> plugins where web views were insufficient.

        - Developed CardAlpha's [Pricing Calculator](https://cardalpha-pricing-calculator.web.app/) web app using <mark>TypeScript</mark> and deployed to <mark>Firebase</mark>.

    - layout: left
      title: Galaksiya, Izmir
      link: www.galaksiya.com
      sub_title: Software Developer Intern
      caption: February 2019 - September 2020 (1 year 8 months)
      description: |
        *Galaksiya is a software development and consultancy company based in Izmir, Turkey.
        The company places high emphasis on internal education to sustain research efforts.*

        - Learned the basics of software development at Galaksiya.
        As an intern, I tested the latest technologies and presented the results to the software development team.
        Having the opportunity to use a wide range of tools and frameworks early in my career has given me the drive to explore new technologies.

        - Developed a product catalog web application.
        Built microservices using the <mark>Micronaut</mark> Framework in <mark>Java</mark>.
        Created a database using <mark>PostgreSQL</mark> and connected it to microservices using <mark>GraphQL</mark>.
        Used <mark>Docker</mark> for containerization, <mark>Docker Swarm</mark> for container orchestration, <mark>Junit</mark> for unit testing, <mark>Selenium</mark> for large-scale testing, and <mark>HTML</mark>, <mark>CSS</mark>, <mark>JavaScript</mark> for the client side.

        - Developed an activity monitoring software to track users' activity.
        Built a REST API using the <mark>Micronaut</mark> Framework in <mark>Java</mark> and a REST client in <mark>Python</mark>.
        Used <mark>Elasticsearch</mark> to store JSON data from the client.
        Visualized the content indexed on <mark>Elasticsearch</mark> using <mark>Kibana</mark> and automated the build/deployment pipeline with <mark>Bash</mark>.

        - Built dozens of web scrapers with <mark>Scrapy-Splash</mark> to extract gigabytes of data daily from various e-commerce websites.
        Prepared extracted data for machine learning model training using <mark>Python</mark>.

        - Performed exploratory data analysis on domain-specific data using <mark>Seaborn</mark>, <mark>Pandas</mark>, <mark>Matplotlib</mark>, and visualized the main characteristics of the data sets.

  - title: Education
    layout: list # (list/text)
    content:
      - layout: left
        title: Ege University
        caption: 2017 - 2021 (GPA: 3.11/4.0)
        sub_title: |
          BSc Computer Science
        description: |
          *Established in 1955, Ege University consistently ranks among the top research universities in Turkey.*

          During my degree at Ege University, I acquired key skills such as teamwork and project management.
          In my first year of college, I spent much of my free time as a committee member of the [Ege Entrepreneurship Society](https://www.egegirisimcilik.com/), organizing technical visits to companies and campus events for students.
          Starting from my second year of college, I worked as a developer, successfully balancing both school and work.

  - title: Software Skills
    layout: text
    content: |
      <mark>Golang</mark> <mark>gRPC</mark> <mark>Python</mark> <mark>JavaScript</mark> <mark>TypeScript</mark> <mark>NodeJS</mark> <mark>Firebase</mark> <mark>Postman</mark> <mark>OpenAPI</mark> <mark>VueJS</mark> <mark>Capacitor</mark> <mark>Tailwind</mark> <mark>CSS</mark> <mark>Github</mark> <mark>Agile</mark> <mark>Scrum</mark> <mark>Kanban</mark> <mark>OpenAPI</mark> <mark>Cloudflare</mark> <mark>Netlify</mark> <mark>Docker</mark> <mark>Docker Compose</mark> <mark>MacOS</mark> <mark>Linux</mark> <mark>Bash</mark> <mark>Terminal</mark>

  # - title: Projects
  #   layout: list
  #   content:
  #     - layout: top-middle
  #       title: Social Media App
  #       github: kadenn/social-media-app
  #       description: |
  #         ONCE DEPLOY ET SONRA EKLE

  # - title: A Little More About Me
  #   layout: text
  #   content: |
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

footer_show_references: true
# references_title: References on request (Override references text)

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
